### ISSUE TITLE
Create Working Pipeline

### ISSUE THREAD

**Issue by stevenrbrandt** [alex-r-bigelow/traveler-integrated#26]
We'd like to have a working pipeline, like https://hub.docker.com/repository/docker/stevenrbrandt/expression_trees
to run traveler-integrated. Ideally before SC19.

It should probably also be based on stevenrbrandt/phylanx.test:working

**Comment by alex-r-bigelow** [comment]
A couple questions / comments on this:
- [ ] The docker issue should be fixed per #27 
- [ ] Should the workflow include Jupyter?
  - [ ] If so, should we worry about collecting OTF2 traces (don't think that's possible with a decorator AFAIK)?
  - [ ] I'm guessing we'd just integrate Jupyter, phylanx, and traveler-integrated all in the same image, instead of trying for some kind of modular docker-compose magic?
  - [ ] At the moment, traveler-integrated relies on loading traces / trees / performance data from files, but a lot of the infrastructure is already in place to stream data directly to its API if Jupyter is running on a separate port in the same container. Does this seem like the right way for them to talk to each other?

**Comment by stevenrbrandt** [comment]
@alex-r-bigelow I would like to see it work in Jupyter, but I'm find for it working from a command line to get started. And yes, a single docker image is what I'm shooting for. It should probably start with "FROM stevenrbrandt/phylanx.test:working".

I don't know how to get the OTF2 data, unless it's the same thing we did in https://github.com/kawilliams/expression-trees.git in whole_pipeline.ipynb, namely, we provide an decorator @Phylanx(performance='x'). Then, after the function runs, we obtain the data from the __perfdata__ field (see send_data.py in the above named repo).

Anyway, to start with, the  goal is to run a phylanx function, collect the performance data from that run, then visualize it, all in one image--in whatever way works. 

BTW, will you be going to SC19?

**Comment by alex-r-bigelow** [comment]
That makes sense. I don't think OTF2 data is available via `__perfdata__` as far as I know... connecting to the trace data is definitely going to be the tricky part that may mess up whatever we plan now.

For now, I'll aim for generating a link to `traveler-integrated` running inside the same docker container, and it will do something similar to how `send_data.py` works... something like:

```
@Phylanx
def fib(n):
    if n < 2:
    ...

visualizeInTraveler(fib)
```
And the output would be a link that you could click that would open the interface in a new tab. Or I guess we could put it in an iframe, but the interface will definitely integrate less elegantly than Katy's did.

(and yes, I'll definitely be at SC19! I might be pushing a survey on the side...)

**Comment by alex-r-bigelow** [comment]
This is kind of the workflow I envisioned:

![zoom](https://user-images.githubusercontent.com/1215873/68892455-5400c900-06e0-11ea-99c4-6f07dbc3f0b0.gif)
